default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  # Usuário padrão do PostgreSQL
  password: <%= ENV['PG_PASSWORD'] || 'admin' %>  # Senha definida como 'admin', ou variável de ambiente

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  primary: &primary_production
    <<: *default
    database: blog_production
    username: postgres  # Usuário padrão do PostgreSQL
    password: <%= ENV['PG_PASSWORD'] || 'admin' %>  # Senha definida como 'admin', ou variável de ambiente
  cache:
    <<: *primary_production
    database: blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_production_cable
    migrations_paths: db/cable_migrate
